import type { I18nText } from '@/types/content'

export const homeCopy: Record<string, I18nText> = {
  eyebrow: { en: 'A living historical record — 1800 to present', gu: 'એક જીવંત ઐતિહાસિક નોંધ — 1800 થી અત્યાર સુધી', hi: 'एक जीवंत ऐतिहासिक अभिलेख — 1800 से अब तक' },
  subtitle: { en: 'From Kanbi roots to a global community.', gu: 'કણબી મૂળથી વૈશ્વિક સમુદાય સુધી.', hi: 'कणबी जड़ों से एक वैश्विक समुदाय तक.' },
  copy: {
    en: 'Explore centuries of agriculture, migration, social change, freedom struggle, entrepreneurship and global diaspora.',
    gu: 'ખેતી, સ્થળાંતર, સામાજિક પરિવર્તન, સ્વાતંત્ર્ય સંગ્રામ, સાહસિકતા અને વૈશ્વિક ડાયસ્પોરાની સદીઓ શોધો.',
    hi: 'कृषि, प्रवासन, सामाजिक परिवर्तन, स्वतंत्रता संग्राम, उद्यमिता और वैश्विक प्रवासी की सदियों का अन्वेषण करें.',
  },
  exploreCta: { en: 'Explore history', gu: 'ઇતિહાસ જુઓ', hi: 'इतिहास देखें' },
  libraryCta: { en: 'Research library', gu: 'સંશોધન પુસ્તકાલય', hi: 'शोध पुस्तकालय' },
  introEyebrow: { en: 'An evolving public record', gu: 'એક વિકસતી જાહેર નોંધ', hi: 'एक विकसित होता सार्वजनिक अभिलेख' },
  introTitleLine1: { en: 'Understanding the', gu: 'પટીદાર વાર્તાને', hi: 'पटीदार कहानी को' },
  introTitleLine2: { en: 'Patidar story', gu: 'સમજવી', hi: 'समझना' },
  introCopy: {
    en: 'This archive brings together the histories of a community shaped by land, movement and collective imagination. It is a place to follow the threads between village, region and world.',
    gu: 'આ આર્કાઇવ જમીન, ગતિ અને સામૂહિક કલ્પના દ્વારા ઘડાયેલા સમુદાયનો ઇતિહાસ એકસાથે લાવે છે. તે ગામ, પ્રદેશ અને વિશ્વ વચ્ચેના તાંતણાઓને અનુસરવાની જગ્યા છે.',
    hi: 'यह अभिलेख भूमि, गति और सामूहिक कल्पना से गढ़े गए समुदाय के इतिहास को एक साथ लाता है। यह गांव, क्षेत्र और विश्व के बीच के सूत्रों को खोजने की जगह है.',
  },
  introReadMore: { en: 'Read the introduction', gu: 'પરિચય વાંચો', hi: 'परिचय पढ़ें' },
  articlesLabel: { en: 'Articles', gu: 'લેખો', hi: 'लेख' },
  peopleLabel: { en: 'People & stories', gu: 'લોકો અને વાર્તાઓ', hi: 'लोग और कहानियां' },
  documentsLabel: { en: 'Research records', gu: 'સંશોધન રેકોર્ડ', hi: 'शोध रिकॉर्ड' },
  sectionsEyebrow: { en: 'Explore the archive', gu: 'આર્કાઇવ જુઓ', hi: 'अभिलेख देखें' },
  sectionsTitleLine1: { en: 'Many histories.', gu: 'ઘણા ઇતિહાસ.', hi: 'कई इतिहास.' },
  sectionsTitleLine2: { en: 'One living story.', gu: 'એક જીવંત વાર્તા.', hi: 'एक जीवंत कहानी.' },
  viewAllSections: { en: 'View all sections', gu: 'બધા વિભાગો જુઓ', hi: 'सभी खंड देखें' },
  timelineEyebrow: { en: 'A chronology of change', gu: 'પરિવર્તનની કાલક્રમ', hi: 'परिवर्तन का कालक्रम' },
  timelineTitleLine1: { en: 'Across time &', gu: 'સમય અને', hi: 'समय और' },
  timelineTitleLine2: { en: 'place', gu: 'સ્થળમાં', hi: 'स्थान में' },
  exploreTimeline: { en: 'Explore timeline', gu: 'સમયરેખા જુઓ', hi: 'समयरेखा देखें' },
  peopleEyebrow: { en: 'People & memory', gu: 'લોકો અને સ્મૃતિ', hi: 'लोग और स्मृति' },
  peopleTitleLine1: { en: 'Lives that', gu: 'જીવન જેણે', hi: 'जीवन जिसने' },
  peopleTitleLine2: { en: 'made history', gu: 'ઇતિહાસ ઘડ્યો', hi: 'इतिहास रचा' },
  meetPeople: { en: 'Meet the people', gu: 'લોકોને મળો', hi: 'लोगों से मिलें' },
  viewProfile: { en: 'View profile', gu: 'પ્રોફાઇલ જુઓ', hi: 'प्रोफ़ाइल देखें' },
  placesEyebrow: { en: 'A geography of belonging', gu: 'સંબંધની ભૂગોળ', hi: 'अपनेपन का भूगोल' },
  placesTitleLine1: { en: 'Places hold', gu: 'સ્થળો સાચવે છે', hi: 'स्थान संजोते हैं' },
  placesTitleLine2: { en: 'the memory', gu: 'સ્મૃતિને', hi: 'स्मृति को' },
  exploreAllPlaces: { en: 'Explore all places', gu: 'બધા સ્થળો જુઓ', hi: 'सभी स्थान देखें' },
  libraryEyebrow: { en: 'Research library', gu: 'સંશોધન પુસ્તકાલય', hi: 'शोध पुस्तकालय' },
  libraryTitleLine1: { en: 'Read the', gu: 'નોંધ', hi: 'अभिलेख' },
  libraryTitleLine2: { en: 'record', gu: 'વાંચો', hi: 'पढ़ें' },
  libraryCopy: {
    en: 'Browse books, papers, community publications and archival documents that help us ask better questions of the past.',
    gu: 'પુસ્તકો, પેપર્સ, સામુદાયિક પ્રકાશનો અને આર્કાઇવલ દસ્તાવેજો બ્રાઉઝ કરો જે ભૂતકાળ વિશે વધુ સારા પ્રશ્નો પૂછવામાં મદદ કરે છે.',
    hi: 'पुस्तकें, शोधपत्र, सामुदायिक प्रकाशन और अभिलेखीय दस्तावेज़ ब्राउज़ करें जो अतीत के बारे में बेहतर प्रश्न पूछने में मदद करते हैं.',
  },
  enterLibrary: { en: 'Enter the library', gu: 'પુસ્તકાલયમાં પ્રવેશ કરો', hi: 'पुस्तकालय में प्रवेश करें' },
  searchEyebrow: { en: 'Search the archive', gu: 'આર્કાઇવ શોધો', hi: 'अभिलेख खोजें' },
  searchTitleLine1: { en: 'What are you', gu: 'તમે શું', hi: 'आप क्या' },
  searchTitleLine2: { en: 'looking for?', gu: 'શોધી રહ્યા છો?', hi: 'खोज रहे हैं?' },
  searchPlaceholder: { en: 'Search people, places, events…', gu: 'લોકો, સ્થળો, ઘટનાઓ શોધો…', hi: 'लोग, स्थान, घटनाएं खोजें…' },
}
