import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { ArrowLeft, ArrowUpRight, BookOpen, MapPin, Search, Users } from 'lucide-react'
import { articles, documents, people, places, sections, timeline } from '@/data/archive'
import { Header } from '@/components/ui/Header'
import { Footer } from '@/components/ui/Footer'
const localeText = { en: { back: 'Back to archive', explore: 'Explore', records: 'records', demo: 'Demonstration content — replace with verified research records.' }, gu: { back: 'આર્કાઇવ પર પાછા જાઓ', explore: 'જુઓ', records: 'રેકોર્ડ', demo: 'ડેમો સામગ્રી — ચકાસેલ સંશોધન રેકોર્ડથી બદલો.' }, hi: { back: 'अभिलेख पर वापस जाएं', explore: 'देखें', records: 'रिकॉर्ड', demo: 'डेमो सामग्री — सत्यापित शोध रिकॉर्ड से बदलें.' } }

function Shell({ locale, children }: { locale: string; children: React.ReactNode }) {
  return <div className="archive-page"><Header locale={locale} /><main>{children}</main><Footer locale={locale} /></div>
}
function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <header className="archive-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{intro && <p>{intro}</p>}</header> }
function Cards({ locale }: { locale: string }) { return <div className="archive-card-grid">{sections.map(section => <Link className="archive-card" key={section.id} href={`/${locale}/sections/${section.slug}`}><img src={section.coverImage?.url} alt={section.coverImage?.alt ?? section.title} /><div><p className="eyebrow">Section · {articles.filter(a => a.sectionId === section.id).length} articles</p><h2>{section.title}</h2><p>{section.description}</p><span>{localeText[locale as keyof typeof localeText]?.explore ?? 'Explore'} <ArrowUpRight /></span></div></Link>)}</div> }
function ArticleBody({ article }: { article: (typeof articles)[number] }) { return <div className="article-body">{article.content.map(block => block.type === 'quote' ? <blockquote key={block.id}>{block.data?.text}<cite>{block.data?.author}</cite></blockquote> : <p key={block.id}>{block.data?.text}</p>)}<div className="reference-panel"><p className="eyebrow">Research note</p><p>This prototype distinguishes documented evidence, scholarly interpretation, community tradition and open questions. Confirm citations against the supplied research edition before publication.</p></div></div> }
function Directory({ locale, kind }: { locale: string; kind: string }) { const isPeople = kind === 'people'; const isPlaces = kind === 'places'; const items = isPeople ? people : isPlaces ? places : documents; return <><Heading eyebrow={isPeople ? 'People & memory' : isPlaces ? 'A geography of belonging' : 'Research library'} title={isPeople ? 'Lives that made history' : isPlaces ? 'Places in the Patidar story' : 'Read the record'} intro={isPeople ? 'Profiles of people whose work, lives and choices shaped the archive.' : isPlaces ? 'Villages, cities and regions connected through movement, work and memory.' : 'Books, papers, records and community publications for careful historical research.'} /><div className="archive-filter"><Search /><input placeholder={`Search ${kind}`} aria-label={`Search ${kind}`} /></div><div className="directory-grid">{items.map((item: any) => <Link key={item.id} className="directory-item" href={`/${locale}/${isPeople ? 'people' : isPlaces ? 'places' : 'library'}/${item.slug ?? item.id}`} >{item.imageUrl && <img src={item.imageUrl} alt={item.name} />}<div><p className="eyebrow">{item.category ?? item.region ?? item.source}</p><h2>{item.name ?? item.title}</h2><p>{item.shortDescription ?? item.description ?? `${item.author} · ${item.year}`}</p><span>View record <ArrowUpRight /></span></div></Link>)}</div></> }

export default async function ArchiveRoute({ params }: { params: Promise<{ locale: string; slug?: string[] }> }) { const { locale, slug = [] } = await params; if (!['en', 'gu', 'hi'].includes(locale)) notFound(); if (slug.length === 0 && locale === 'en') redirect('/'); const [section, detail] = slug; let content: React.ReactNode
 if (!section) content = <><Heading eyebrow="The living archive" title="The story of a community" intro="A connected historical research experience tracing Patidar life from Kanbi roots through Gujarat, migration and global belonging." /><Cards locale={locale} /></>
 else if (section === 'history') content = <><Heading eyebrow="A chronology of change" title="Across time & place" intro="Follow a layered history of agriculture, identity, public life and movement." /><div className="long-timeline">{timeline.map(event => <article key={event.id}><span>{event.year}</span><div><p className="eyebrow">{event.category} · {event.region}</p><h2>{event.title}</h2><p>{event.description}</p></div></article>)}</div></>
 else if (section === 'sections' && !detail) content = <><Heading eyebrow="Explore the archive" title="Chapters of the story" intro="Browse the major themes and research paths in this evolving public record." /><Cards locale={locale} /></>
 else if (section === 'sections' && detail) { const found = sections.find(s => s.slug === detail); if (!found) notFound(); const related = articles.filter(a => a.sectionId === found.id); content = <><Heading eyebrow="Historical section" title={found.title} intro={found.description} /><div className="section-detail"><img src={found.coverImage?.url} alt={found.coverImage?.alt ?? found.title} /><div><p>{`This chapter brings together the archive's working notes on ${found.title.toLowerCase()}, with relationships to people, places, documents and events.`}</p><h2>Featured articles</h2>{related.map(article => <Link className="article-row" key={article.id} href={`/${locale}/sections/${found.slug}/${article.slug}`}><span>{article.readingTime} min read</span><strong>{article.title}</strong><ArrowUpRight /></Link>)}</div></div></> }
 else if (section === 'sections' && detail) content = null
 else if (section === 'people' || section === 'places' || section === 'library') { const collection = section === 'people' ? people : section === 'places' ? places : documents; if (detail) { const item: any = collection.find((x: any) => (x.slug ?? x.id) === detail); if (!item) notFound(); content = <><Heading eyebrow={section === 'people' ? 'Person record' : section === 'places' ? 'Place record' : 'Document record'} title={item.name ?? item.title} intro={item.shortDescription ?? item.description ?? `${item.author} · ${item.year}`} /><div className="record-layout"><div className="record-meta"><p className="eyebrow">Archive record</p><p>{item.region ?? item.category ?? item.source}</p><p>{item.birthYear ? `${item.birthYear} — ${item.deathYear ?? 'present'}` : item.year}</p></div><div className="article-body"><h2>Historical context</h2><p>{item.biography ?? item.historicalSignificance ?? item.description ?? 'This record is prepared as a structured research placeholder. Add verified context, citations and related materials through the future CMS.'}</p><div className="reference-panel"><p className="eyebrow">Related sources</p><p>References, documents and linked records will appear here as the archive grows.</p></div></div></div></> } else content = <Directory locale={locale} kind={section} /> }
 else if (section === 'timeline') content = <><Heading eyebrow="A chronology of change" title="Timeline" intro="Key moments and periods currently represented in the demonstration archive." /><div className="long-timeline">{timeline.map(event => <article key={event.id}><span>{event.year}</span><div><p className="eyebrow">{event.category}</p><h2>{event.title}</h2><p>{event.description}</p></div></article>)}</div></>
 else if (section === 'regions' || section === 'diaspora') content = <><Heading eyebrow={section === 'regions' ? 'Gujarat' : 'Beyond Gujarat'} title={section === 'regions' ? 'Regions of connection' : 'A global community'} intro="Explore this connected geography through carefully sourced stories, places and movement." /><div className="feature-note"><MapPin /><p>Interactive map and regional records are ready for future verified content. Start with the related sections, people and places below.</p></div><Cards locale={locale} /></>
 else if (section === 'about' || section === 'sources') content = <><Heading eyebrow="Institutional record" title={section === 'about' ? 'About this archive' : 'Sources & references'} intro="A research interface designed to make historical uncertainty visible and connections easy to follow." /><div className="article-body institutional"><h2>{section === 'about' ? 'Methodology' : 'Working source categories'}</h2><p>The archive separates documented evidence, scholarly interpretation, community tradition and open questions. This approach respects the importance of community memory while keeping claims transparent and revisable.</p><p>Future editions will attach each article, person and place to references, page numbers, source credits and translations in English, Gujarati and Hindi.</p></div></>
 else if (section === 'search') content = <><Heading eyebrow="Research interface" title="Search the archive" intro="Find articles, people, places, documents and timeline events across the collection." /><div className="archive-filter archive-filter-large"><Search /><input placeholder="Search people, places, events..." autoFocus aria-label="Search archive" /></div><div className="feature-note"><BookOpen /><p>Search results will become data-driven when the mock provider is replaced with the CMS.</p></div></>
 else notFound(); return <Shell locale={locale}>{content}</Shell> }

export async function generateStaticParams() { return ['en', 'gu', 'hi'].map(locale => ({ locale })) }
